### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [hsorathia/cash_flow#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by famefox2** [comment]
Hello its kevin

**Comment by hsorathia** [comment]
Hello this is Habib and this is group 6 from section 1.

**Comment by christinemnguyen** [comment]
Hello! This is Christine

**Comment by ProfRojas** [comment]
Please have all of your teammates respond. Otherwise, you will only receive partial credit for the GitHub portion.

**Comment by maruko7290** [comment]
Hello, This is Anh, from Section1, group 6

**Comment by ProfRojas** [comment]
Thanks!
