### ISSUE TITLE
Sign Up Page Implementation

### ISSUE THREAD

**Issue by christinemnguyen** [hsorathia/cash_flow#12]
I'm having some problems implementing the Sign Up page because right now it's only a page that does not really accept or keep data

**Comment by hsorathia** [comment]
That's fine, I can help you with it when you're free. What have you tried implementing so far?

**Comment by christinemnguyen** [comment]
The prof is making a video for it soon, so I should be able to handle it by latest tomorrow night. In the meantime I'm going to try implementing using his slides or youtube

**Comment by hsorathia** [comment]
finished this yesterday
