### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by hsorathia** [hsorathia/cash_flow#5]
This is the home / index page that everyone will see when they log in. We need a page to introduce them to our task and a navigation bar so they can log in or jump into making their comparison.

**Comment by maruko7290** [comment]
@hsorathia To clarify, Is it the home page before they log in with navigation bar?

**Comment by maruko7290** [comment]
I can work on this.

**Comment by hsorathia** [comment]
I accidentally finished part of this so all you will have to do is add a button to prompt the user to log in

**Comment by hsorathia** [comment]
finished this 10 days ago
